// ==================== IMPORTS ====================
const Invoice = require("../models/Invoice");
const Sale = require("../models/Sale");
const Purchase = require("../models/Purchase");
const { getNepaliCurrentDateTime } = require("../utils/dateUtils");
const nodemailer = require("nodemailer");
const PDFDocument = require("pdfkit");

// ==================== HELPERS ====================

const formatCurrency = (amount = 0) => `Rs ${Number(amount).toFixed(2)}`;

const createEmailTransporter = () => {
  const { EMAIL_SERVICE, EMAIL_USER, EMAIL_PASSWORD } = process.env;

  if (!EMAIL_SERVICE || !EMAIL_USER || !EMAIL_PASSWORD) {
    throw new Error("Email service is not configured. Please set EMAIL_SERVICE, EMAIL_USER, and EMAIL_PASSWORD.");
  }

  return nodemailer.createTransport({
    service: EMAIL_SERVICE,
    auth: {
      user: EMAIL_USER,
      pass: EMAIL_PASSWORD,
    },
  });
};

const buildInvoiceEmailHtml = (invoice) => {
  return `
    <div style="font-family:Arial,sans-serif;max-width:720px;margin:0 auto;color:#111827;">
      <h2 style="margin-bottom:8px;">Invoice ${invoice.invoiceNumber}</h2>
      <p style="margin-top:0;color:#4b5563;">Please find your invoice attached as a PDF.</p>

      <div style="margin:16px 0;padding:12px;border:1px solid #e5e7eb;border-radius:8px;background:#f9fafb;">
        <p style="margin:4px 0;"><strong>${invoice.type === "sale" ? "Customer" : "Supplier"}:</strong> ${invoice.customerName || "N/A"}</p>
        <p style="margin:4px 0;"><strong>Issue Date:</strong> ${new Date(invoice.issueDate).toLocaleDateString()}</p>
        <p style="margin:4px 0;"><strong>Due Date:</strong> ${new Date(invoice.dueDate).toLocaleDateString()}</p>
        <p style="margin:4px 0;"><strong>Total:</strong> ${formatCurrency(invoice.total || 0)}</p>
        <p style="margin:4px 0;"><strong>Status:</strong> ${invoice.paymentStatus}</p>
      </div>

      <p style="margin-top:24px;color:#6b7280;font-size:12px;">Generated by BizTrack</p>
    </div>
  `;
};

const buildInvoicePdfBuffer = (invoice) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const heading = `Invoice ${invoice.invoiceNumber}`;
      doc.fontSize(22).text(heading, { align: "left" });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor("#4b5563").text("Generated by BizTrack");
      doc.moveDown(1);

      doc.fillColor("#111827");
      doc.fontSize(12).text(`${invoice.type === "sale" ? "Customer" : "Supplier"}: ${invoice.customerName || "N/A"}`);
      doc.text(`Issue Date: ${new Date(invoice.issueDate).toLocaleDateString()}`);
      doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`);
      doc.text(`Payment Status: ${invoice.paymentStatus}`);
      doc.moveDown(1);

      const tableStartY = doc.y;
      const itemX = 50;
      const qtyX = 300;
      const priceX = 360;
      const totalX = 460;

      doc.fontSize(12).text("Item", itemX, tableStartY);
      doc.text("Qty", qtyX, tableStartY);
      doc.text("Price", priceX, tableStartY);
      doc.text("Total", totalX, tableStartY);

      doc.moveTo(50, tableStartY + 18).lineTo(545, tableStartY + 18).strokeColor("#d1d5db").stroke();

      let rowY = tableStartY + 26;
      (invoice.items || []).forEach((item) => {
        if (rowY > 740) {
          doc.addPage();
          rowY = 50;
        }
        doc.fontSize(11).fillColor("#111827").text(item.name || "-", itemX, rowY, { width: 240 });
        doc.text(String(item.quantity ?? 0), qtyX, rowY, { width: 40, align: "right" });
        doc.text(formatCurrency(item.price || 0), priceX, rowY, { width: 90, align: "right" });
        doc.text(formatCurrency(item.total || 0), totalX, rowY, { width: 85, align: "right" });
        rowY += 24;
      });

      const totalsY = rowY + 12;
      doc.moveTo(320, totalsY - 8).lineTo(545, totalsY - 8).strokeColor("#d1d5db").stroke();

      doc.fontSize(12).fillColor("#111827");
      doc.text("Subtotal", 360, totalsY, { width: 90, align: "right" });
      doc.text(formatCurrency(invoice.subtotal || 0), 460, totalsY, { width: 85, align: "right" });
      doc.text("Tax", 360, totalsY + 20, { width: 90, align: "right" });
      doc.text(formatCurrency(invoice.tax || 0), 460, totalsY + 20, { width: 85, align: "right" });
      doc.text("Discount", 360, totalsY + 40, { width: 90, align: "right" });
      doc.text(formatCurrency(invoice.discount || 0), 460, totalsY + 40, { width: 85, align: "right" });

      doc.fontSize(14).font("Helvetica-Bold");
      doc.text("Total", 360, totalsY + 68, { width: 90, align: "right" });
      doc.text(formatCurrency(invoice.total || 0), 460, totalsY + 68, { width: 85, align: "right" });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

// Helper function to generate invoice from sale
const generateInvoiceFromSale = async (sale, userInfo = {}) => {
  try {
    // Calculate due date (30 days from now)
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 30);

    // Use the same invoice number as the sale
    const invoiceNumber = sale.invoiceNumber;

    const invoiceData = {
      invoiceNumber: invoiceNumber,
      type: "sale",
      relatedId: sale._id,
      relatedModel: "Sale",
      customerName: sale.customerName,
      customerEmail: sale.customerEmail,
      customerPhone: sale.customerPhone,
      items: sale.items.map(item => ({
        inventoryId: item.inventoryId,
        name: item.name,
        quantity: item.quantity,
        price: item.price,
        total: item.total,
      })),
      subtotal: sale.subtotal,
      tax: sale.tax,
      discount: sale.discount,
      total: sale.total,
      dueDate: dueDate,
      issueDate: sale.createdAt || new Date(),
      paymentStatus: sale.paymentStatus,
      paidAmount: sale.paidAmount,
      paymentMethod: sale.paymentMethod,
      status: sale.paymentStatus === "paid" ? "paid" : "sent",
      autoGenerated: true,
      generatedFrom: "sale",
      createdBy: userInfo,
      notes: sale.notes,
    };

    const invoice = await Invoice.create(invoiceData);
    return invoice;
  } catch (error) {
    console.error("Error generating invoice from sale:", error);
    throw error;
  }
};

// Helper function to generate invoice from purchase
const generateInvoiceFromPurchase = async (purchase, userInfo = {}) => {
  try {
    // Calculate due date (30 days from now)
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 30);

    // Use the same invoice number as the purchase
    const invoiceNumber = purchase.purchaseNumber;

    const invoiceData = {
      invoiceNumber: invoiceNumber,
      type: "purchase",
      relatedId: purchase._id,
      relatedModel: "Purchase",
      customerName: purchase.supplierName,
      customerEmail: purchase.supplierEmail,
      customerPhone: purchase.supplierPhone,
      items: purchase.items.map(item => ({
        inventoryId: item.inventoryId,
        name: item.name,
        quantity: item.quantity,
        price: item.cost, // Use cost for purchase invoices
        total: item.total,
      })),
      subtotal: purchase.subtotal,
      tax: purchase.tax,
      shipping: purchase.shipping,
      total: purchase.total,
      dueDate: dueDate,
      issueDate: purchase.createdAt || new Date(),
      paymentStatus: purchase.paymentStatus,
      paidAmount: purchase.paidAmount,
      paymentMethod: purchase.paymentMethod,
      status: purchase.paymentStatus === "paid" ? "paid" : "sent",
      autoGenerated: true,
      generatedFrom: "purchase",
      createdBy: userInfo,
      notes: purchase.notes,
    };

    const invoice = await Invoice.create(invoiceData);
    return invoice;
  } catch (error) {
    console.error("Error generating invoice from purchase:", error);
    throw error;
  }
};

// ==================== READ ENDPOINTS ====================

// Get all invoices
exports.getAllInvoices = async (req, res) => {
  try {
    const { 
      type, 
      status, 
      paymentStatus, 
      paymentMethod,
      generatedFrom,
      autoGenerated,
      search, 
      customerName,
      dateFrom,
      dateTo,
      dueDateFrom,
      dueDateTo,
      amountFrom,
      amountTo,
      createdBy,
      sortBy,
      sortOrder,
      relatedId, // Add this for finding invoices by sale/purchase ID
      page = 1, 
      limit = 10 
    } = req.query;
    
    // Build filter object
    const filter = {};
    
    // Basic filters
    if (type) filter.type = type;
    if (status) filter.status = status;
    if (paymentStatus) filter.paymentStatus = paymentStatus;
    if (paymentMethod) filter.paymentMethod = paymentMethod;
    if (generatedFrom) filter.generatedFrom = generatedFrom;
    if (autoGenerated) filter.autoGenerated = autoGenerated === 'true';
    if (relatedId) filter.relatedId = relatedId; // Filter by related sale/purchase ID
    
    // Text search filters
    if (search) {
      filter.$or = [
        { invoiceNumber: { $regex: search, $options: 'i' } },
        { customerName: { $regex: search, $options: 'i' } },
        { customerEmail: { $regex: search, $options: 'i' } },
        { notes: { $regex: search, $options: 'i' } },
      ];
    }
    
    if (customerName) {
      filter.customerName = { $regex: customerName, $options: 'i' };
    }
    
    if (createdBy) {
      filter['createdBy.name'] = { $regex: createdBy, $options: 'i' };
    }
    
    // Date range filters
    if (dateFrom || dateTo) {
      filter.issueDate = {};
      if (dateFrom) filter.issueDate.$gte = new Date(dateFrom);
      if (dateTo) {
        const endDate = new Date(dateTo);
        endDate.setHours(23, 59, 59, 999); // End of day
        filter.issueDate.$lte = endDate;
      }
    }
    
    if (dueDateFrom || dueDateTo) {
      filter.dueDate = {};
      if (dueDateFrom) filter.dueDate.$gte = new Date(dueDateFrom);
      if (dueDateTo) {
        const endDate = new Date(dueDateTo);
        endDate.setHours(23, 59, 59, 999); // End of day
        filter.dueDate.$lte = endDate;
      }
    }
    
    // Amount range filters
    if (amountFrom || amountTo) {
      filter.total = {};
      if (amountFrom) filter.total.$gte = parseFloat(amountFrom);
      if (amountTo) filter.total.$lte = parseFloat(amountTo);
    }

    // Build sort object
    let sort = { createdAt: 1 }; // Default sort - ascending (oldest first)
    if (sortBy) {
      const order = sortOrder === 'asc' ? 1 : -1;
      sort = { [sortBy]: order };
    }

    const skip = (page - 1) * limit;
    const invoices = await Invoice.find(filter)
      .populate('items.inventoryId')
      .populate('relatedId')
      .sort(sort)
      .skip(skip)
      .limit(parseInt(limit));

    const total = await Invoice.countDocuments(filter);

    // Fetch payments from related Sales/Purchases for each invoice
    const invoicesWithPayments = await Promise.all(
      invoices.map(async (invoice) => {
        const invoiceObj = invoice.toObject();
        let payments = [];
        let scheduledAmount = 0;
        
        if (invoice.relatedId) {
          try {
            if (invoice.type === 'sale') {
              const sale = await Sale.findById(invoice.relatedId);
              if (sale) {
                payments = sale.payments || [];
                scheduledAmount = sale.scheduledAmount || 0;
              }
            } else if (invoice.type === 'purchase') {
              const purchase = await Purchase.findById(invoice.relatedId);
              if (purchase) {
                payments = purchase.payments || [];
                scheduledAmount = purchase.scheduledAmount || 0;
              }
            }
          } catch (fetchError) {
            console.error('⚠️ Failed to fetch payments for invoice:', invoice._id, fetchError);
          }
        }
        
        invoiceObj.payments = payments;
        invoiceObj.scheduledAmount = scheduledAmount;
        return invoiceObj;
      })
    );

    res.json({
      invoices: invoicesWithPayments,
      pagination: {
        current: parseInt(page),
        pages: Math.ceil(total / limit),
        total,
      },
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// Get single invoice
exports.getInvoiceById = async (req, res) => {
  try {
    const invoice = await Invoice.findById(req.params.id)
      .populate('items.inventoryId')
      .populate('relatedId');
    if (!invoice) {
      return res.status(404).json({ error: "Invoice not found" });
    }
    
    // Fetch payments from the related Sale or Purchase
    let payments = [];
    let scheduledAmount = 0;
    if (invoice.relatedId) {
      try {
        if (invoice.type === 'sale') {
          const sale = await Sale.findById(invoice.relatedId);
          if (sale) {
            payments = sale.payments || [];
            scheduledAmount = sale.scheduledAmount || 0;
          }
        } else if (invoice.type === 'purchase') {
          const purchase = await Purchase.findById(invoice.relatedId);
          if (purchase) {
            payments = purchase.payments || [];
            scheduledAmount = purchase.scheduledAmount || 0;
          }
        }
      } catch (fetchError) {
        console.error('⚠️ Failed to fetch payments from related document:', fetchError);
      }
    }
    
    // Add payments and scheduledAmount to invoice response
    const invoiceWithPayments = invoice.toObject();
    invoiceWithPayments.payments = payments;
    invoiceWithPayments.scheduledAmount = scheduledAmount;
    
    res.json(invoiceWithPayments);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// ==================== WRITE ENDPOINTS ====================

// Create new invoice
exports.createInvoice = async (req, res) => {
  try {
    const invoiceData = {
      ...req.body,
      createdBy: {
        userId: req.user?.id || req.user?._id,
        name: req.user?.name || "Unknown User",
        role: req.user?.role || "staff",
      },
    };

    // Generate invoice number if not provided
    if (!invoiceData.invoiceNumber) {
      const type = invoiceData.type || "sale";
      const count = await Invoice.countDocuments({ type: type });
      const prefix = type === 'sale' ? 'INV' : 'PINV';
      invoiceData.invoiceNumber = `${prefix}-${String(count + 1).padStart(6, '0')}`;
    }

    const invoice = await Invoice.create(invoiceData);
    const populatedInvoice = await Invoice.findById(invoice._id)
      .populate('items.inventoryId')
      .populate('relatedId');
    
    res.status(201).json(populatedInvoice);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

// Update invoice
exports.updateInvoice = async (req, res) => {
  try {
    const invoice = await Invoice.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true }
    ).populate('items.inventoryId').populate('relatedId');
    
    if (!invoice) {
      return res.status(404).json({ error: "Invoice not found" });
    }
    res.json(invoice);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

// Delete invoice
exports.deleteInvoice = async (req, res) => {
  try {
    const invoice = await Invoice.findByIdAndDelete(req.params.id);
    if (!invoice) {
      return res.status(404).json({ error: "Invoice not found" });
    }
    res.json({ message: "Invoice deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// Generate invoice from sale
exports.generateFromSale = async (req, res) => {
  try {
    const { saleId } = req.params;
    
    // Check if invoice already exists for this sale
    const existingInvoice = await Invoice.findOne({ 
      relatedId: saleId, 
      relatedModel: "Sale" 
    });
    
    if (existingInvoice) {
      return res.status(400).json({ 
        error: "Invoice already exists for this sale",
        invoice: existingInvoice 
      });
    }

    const sale = await Sale.findById(saleId).populate('items.inventoryId');
    if (!sale) {
      return res.status(404).json({ error: "Sale not found" });
    }

    const userInfo = {
      userId: req.user?.id || req.user?._id,
      name: req.user?.name || "Unknown User",
      role: req.user?.role || "staff",
    };

    const invoice = await generateInvoiceFromSale(sale, userInfo);
    const populatedInvoice = await Invoice.findById(invoice._id)
      .populate('items.inventoryId')
      .populate('relatedId');

    res.status(201).json(populatedInvoice);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

// Generate invoice from purchase
exports.generateFromPurchase = async (req, res) => {
  try {
    const { purchaseId } = req.params;
    
    // Check if invoice already exists for this purchase
    const existingInvoice = await Invoice.findOne({ 
      relatedId: purchaseId, 
      relatedModel: "Purchase" 
    });
    
    if (existingInvoice) {
      return res.status(400).json({ 
        error: "Invoice already exists for this purchase",
        invoice: existingInvoice 
      });
    }

    const purchase = await Purchase.findById(purchaseId).populate('items.inventoryId');
    if (!purchase) {
      return res.status(404).json({ error: "Purchase not found" });
    }

    const userInfo = {
      userId: req.user?.id || req.user?._id,
      name: req.user?.name || "Unknown User",
      role: req.user?.role || "staff",
    };

    const invoice = await generateInvoiceFromPurchase(purchase, userInfo);
    const populatedInvoice = await Invoice.findById(invoice._id)
      .populate('items.inventoryId')
      .populate('relatedId');

    res.status(201).json(populatedInvoice);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

// ==================== PAYMENT ENDPOINTS ====================

// Record one or more payments for an invoice
exports.recordInvoicePayment = async (req, res) => {
  try {
    const invoice = await Invoice.findById(req.params.id);
    if (!invoice) {
      return res.status(404).json({ error: `Invoice not found (id: ${req.params.id})` });
    }

    if (!invoice.relatedId) {
      return res.status(400).json({ error: "Invoice has no linked purchase or sale" });
    }

    // Normalise: support both single { amount, date, method, notes }
    // and batch { payments: [{ amount, date, method, notes }, ...] }
    let paymentsToRecord;
    if (Array.isArray(req.body.payments)) {
      paymentsToRecord = req.body.payments;
    } else {
      paymentsToRecord = [req.body];
    }

    // Validate all amounts upfront
    for (const p of paymentsToRecord) {
      const amt = parseFloat(p.amount);
      if (!amt || amt <= 0) {
        return res.status(400).json({ error: "Each payment amount must be greater than 0" });
      }
    }

    const currentDate = new Date();
    currentDate.setHours(0, 0, 0, 0);

    const buildRecord = (p) => {
      const paymentDate = p.date ? new Date(p.date) : new Date();
      const paymentDateOnly = new Date(paymentDate);
      paymentDateOnly.setHours(0, 0, 0, 0);
      const isScheduled = paymentDateOnly > currentDate;
      return {
        amount: parseFloat(p.amount),
        date: paymentDate,
        method: p.method || "cash",
        notes: p.notes || "",
        status: isScheduled ? "scheduled" : "completed",
        isScheduled,
      };
    };

    const records = paymentsToRecord.map(buildRecord);
    const totalNewPaid = records.filter(r => !r.isScheduled).reduce((s, r) => s + r.amount, 0);
    const totalNewScheduled = records.filter(r => r.isScheduled).reduce((s, r) => s + r.amount, 0);
    const totalNew = totalNewPaid + totalNewScheduled;

    let lastMethod = records[records.length - 1].method;

    if (invoice.type === "purchase") {
      const purchase = await Purchase.findById(invoice.relatedId);
      if (!purchase) return res.status(404).json({ error: `Related purchase not found (relatedId: ${invoice.relatedId})` });

      const currentPaid = purchase.paidAmount || 0;
      const currentScheduled = purchase.scheduledAmount || 0;
      const remaining = purchase.total - currentPaid - currentScheduled;

      if (totalNew > remaining + 0.001) {
        return res.status(400).json({
          error: `Total payment (Rs ${totalNew.toFixed(2)}) exceeds remaining balance (Rs ${remaining.toFixed(2)})`
        });
      }

      purchase.payments = purchase.payments || [];
      records.forEach(r => {
        const { isScheduled, ...record } = r;
        purchase.payments.push(record);
      });

      purchase.paidAmount = currentPaid + totalNewPaid;
      purchase.scheduledAmount = currentScheduled + totalNewScheduled;

      const totalPlanned = purchase.paidAmount + purchase.scheduledAmount;
      if (purchase.paidAmount >= purchase.total) {
        purchase.paymentStatus = "paid";
        if (purchase.status === "pending") purchase.status = "received";
      } else if (totalPlanned >= purchase.total) {
        purchase.paymentStatus = "scheduled";
      } else if (purchase.paidAmount > 0 || purchase.scheduledAmount > 0) {
        purchase.paymentStatus = "partial";
      } else {
        purchase.paymentStatus = "unpaid";
      }

      await purchase.save();

      invoice.paymentStatus = purchase.paymentStatus === 'scheduled' ? 'partial' : purchase.paymentStatus;
      invoice.paidAmount = purchase.paidAmount;
      invoice.paymentMethod = lastMethod;
      invoice.status = purchase.paymentStatus === "paid" ? "paid" : "sent";
      await invoice.save();

    } else if (invoice.type === "sale") {
      const sale = await Sale.findById(invoice.relatedId);
      if (!sale) return res.status(404).json({ error: `Related sale not found (relatedId: ${invoice.relatedId})` });

      const currentPaid = sale.paidAmount || 0;
      const currentScheduled = sale.scheduledAmount || 0;
      const remaining = sale.total - currentPaid - currentScheduled;

      if (totalNew > remaining + 0.001) {
        return res.status(400).json({
          error: `Total payment (Rs ${totalNew.toFixed(2)}) exceeds remaining balance (Rs ${remaining.toFixed(2)})`
        });
      }

      sale.payments = sale.payments || [];
      records.forEach(r => {
        const { isScheduled, ...record } = r;
        sale.payments.push(record);
      });

      sale.paidAmount = currentPaid + totalNewPaid;
      sale.scheduledAmount = currentScheduled + totalNewScheduled;

      const totalPlanned = sale.paidAmount + sale.scheduledAmount;
      if (sale.paidAmount >= sale.total) {
        sale.paymentStatus = "paid";
      } else if (totalPlanned >= sale.total) {
        sale.paymentStatus = "scheduled";
      } else if (sale.paidAmount > 0 || sale.scheduledAmount > 0) {
        sale.paymentStatus = "partial";
      } else {
        sale.paymentStatus = "unpaid";
      }

      await sale.save();

      invoice.paymentStatus = sale.paymentStatus === 'scheduled' ? 'partial' : sale.paymentStatus;
      invoice.paidAmount = sale.paidAmount;
      invoice.paymentMethod = lastMethod;
      invoice.status = sale.paymentStatus === "paid" ? "paid" : "sent";
      await invoice.save();

    } else {
      return res.status(400).json({ error: `Unknown invoice type: ${invoice.type}` });
    }

    // Return the updated invoice with fresh payments from the related doc
    const updatedInvoice = await Invoice.findById(invoice._id)
      .populate("items.inventoryId")
      .populate("relatedId");

    let payments = [];
    let scheduledAmount = 0;
    const relatedDocId = updatedInvoice.relatedId?._id || updatedInvoice.relatedId;
    if (relatedDocId) {
      if (invoice.type === "purchase") {
        const purchase = await Purchase.findById(relatedDocId);
        if (purchase) { payments = purchase.payments || []; scheduledAmount = purchase.scheduledAmount || 0; }
      } else if (invoice.type === "sale") {
        const sale = await Sale.findById(relatedDocId);
        if (sale) { payments = sale.payments || []; scheduledAmount = sale.scheduledAmount || 0; }
      }
    }

    const result = updatedInvoice.toObject();
    result.payments = payments;
    result.scheduledAmount = scheduledAmount;
    res.json(result);
  } catch (err) {
    console.error("❌ recordInvoicePayment error:", err);
    res.status(400).json({ error: err.message });
  }
};

// Update invoice payment status
exports.updatePaymentStatus = async (req, res) => {
  try {
    const { paymentStatus, paidAmount, paymentMethod } = req.body;
    
    const invoice = await Invoice.findById(req.params.id);
    if (!invoice) {
      return res.status(404).json({ error: "Invoice not found" });
    }

    // Validate payment amount
    if (paidAmount > invoice.total) {
      return res.status(400).json({ 
        error: `Payment amount cannot exceed total amount (${invoice.total})` 
      });
    }

    // Update invoice
    invoice.paymentStatus = paymentStatus;
    invoice.paidAmount = paidAmount || 0;
    if (paymentMethod) invoice.paymentMethod = paymentMethod;
    
    // Update status based on payment
    if (paymentStatus === "paid") {
      invoice.status = "paid";
    } else if (paymentStatus === "partial") {
      invoice.status = "sent";
    }

    await invoice.save();

    // SYNC: Update the related Sale or Purchase
    if (invoice.relatedId) {
      try {
        if (invoice.type === 'sale') {
          const Sale = require('../models/Sale');
          const sale = await Sale.findById(invoice.relatedId);
          if (sale) {
            sale.paymentStatus = paymentStatus;
            sale.paidAmount = paidAmount || 0;
            if (paymentMethod) sale.paymentMethod = paymentMethod;
            await sale.save();
            console.log(`✅ Synced payment update to Sale ${sale._id}`);
          }
        } else if (invoice.type === 'purchase') {
          const Purchase = require('../models/Purchase');
          const purchase = await Purchase.findById(invoice.relatedId);
          if (purchase) {
            purchase.paymentStatus = paymentStatus;
            purchase.paidAmount = paidAmount || 0;
            if (paymentMethod) purchase.paymentMethod = paymentMethod;
            await purchase.save();
            console.log(`✅ Synced payment update to Purchase ${purchase._id}`);
          }
        }
      } catch (syncError) {
        console.error('⚠️ Failed to sync payment to related document:', syncError);
        // Don't fail the invoice update if sync fails
      }
    }

    const populatedInvoice = await Invoice.findById(invoice._id)
      .populate('items.inventoryId')
      .populate('relatedId');

    res.json(populatedInvoice);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

// Get invoice statistics
exports.getInvoiceStats = async (req, res) => {
  try {
    const stats = await Invoice.aggregate([
      {
        $group: {
          _id: null,
          totalInvoices: { $sum: 1 },
          totalAmount: { $sum: "$total" },
          paidAmount: { $sum: "$paidAmount" },
          pendingAmount: { $sum: { $subtract: ["$total", "$paidAmount"] } },
          salesInvoices: {
            $sum: { $cond: [{ $eq: ["$type", "sale"] }, 1, 0] }
          },
          purchaseInvoices: {
            $sum: { $cond: [{ $eq: ["$type", "purchase"] }, 1, 0] }
          },
          paidInvoices: {
            $sum: { $cond: [{ $eq: ["$paymentStatus", "paid"] }, 1, 0] }
          },
          unpaidInvoices: {
            $sum: { $cond: [{ $eq: ["$paymentStatus", "unpaid"] }, 1, 0] }
          },
          partialInvoices: {
            $sum: { $cond: [{ $eq: ["$paymentStatus", "partial"] }, 1, 0] }
          },
        }
      }
    ]);

    const result = stats[0] || {
      totalInvoices: 0,
      totalAmount: 0,
      paidAmount: 0,
      pendingAmount: 0,
      salesInvoices: 0,
      purchaseInvoices: 0,
      paidInvoices: 0,
      unpaidInvoices: 0,
      partialInvoices: 0,
    };

    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// ==================== EMAIL ENDPOINT ====================

exports.sendInvoiceEmail = async (req, res) => {
  try {
    const invoice = await Invoice.findById(req.params.id);
    if (!invoice) {
      return res.status(404).json({ error: "Invoice not found" });
    }

    const recipientEmail = (req.body?.email || invoice.customerEmail || "").trim();
    if (!recipientEmail) {
      return res.status(400).json({ error: "Recipient email is required" });
    }

    const transporter = createEmailTransporter();
    const subject = `Invoice ${invoice.invoiceNumber} - BizTrack`;
    const pdfBuffer = await buildInvoicePdfBuffer(invoice);
    const text = [
      `Invoice Number: ${invoice.invoiceNumber}`,
      `${invoice.type === "sale" ? "Customer" : "Supplier"}: ${invoice.customerName || "N/A"}`,
      `Total: ${formatCurrency(invoice.total || 0)}`,
      `Issue Date: ${new Date(invoice.issueDate).toLocaleDateString()}`,
      `Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`,
      `Payment Status: ${invoice.paymentStatus}`,
      "",
      "The invoice PDF is attached with this email.",
    ].join("\n");

    const info = await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: recipientEmail,
      subject,
      text,
      html: buildInvoiceEmailHtml(invoice),
      attachments: [
        {
          filename: `${invoice.invoiceNumber}.pdf`,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });

    res.json({
      message: `Invoice emailed successfully to ${recipientEmail}`,
      invoiceId: invoice._id,
      recipientEmail,
      messageId: info.messageId,
    });
  } catch (err) {
    res.status(500).json({ error: err.message || "Failed to send invoice email" });
  }
};

// Export helper functions for use in other controllers
module.exports.generateInvoiceFromSale = generateInvoiceFromSale;
module.exports.generateInvoiceFromPurchase = generateInvoiceFromPurchase;

