import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import Layout from '../layout/Layout';
import InvoiceStats from './Invoices/InvoiceStats';
import InvoiceFilters from './Invoices/InvoiceFilters';
import InvoiceTable from './Invoices/InvoiceTable';
import InvoiceDetailsModal from './Invoices/InvoiceDetailsModal';
import PaymentUpdateModal from './Invoices/PaymentUpdateModal';
import { Invoice, InvoiceStats as IInvoiceStats, InvoiceFilters as IInvoiceFilters, InvoiceResponse } from './Invoices/types';
import { buildQueryString } from './Invoices/utils';
import { invoicesAPI } from '../services/api';

const Invoices: React.FC = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const highlightInvoiceId = searchParams.get('highlight');
  
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [highlightedInvoice, setHighlightedInvoice] = useState<Invoice | null>(null);
  const [stats, setStats] = useState<IInvoiceStats>({
    totalInvoices: 0,
    totalAmount: 0,
    paidAmount: 0,
    pendingAmount: 0,
    salesInvoices: 0,
    purchaseInvoices: 0,
    paidInvoices: 0,
    unpaidInvoices: 0,
    partialInvoices: 0,
  });
  const [filters, setFilters] = useState<IInvoiceFilters>({
    type: '',
    status: '',
    paymentStatus: '',
    paymentMethod: '',
    generatedFrom: '',
    autoGenerated: '',
    search: '',
    customerName: '',
    dateFrom: '',
    dateTo: '',
    dueDateFrom: '',
    dueDateTo: '',
    amountFrom: undefined,
    amountTo: undefined,
    createdBy: '',
    page: 1,
    limit: 10,
    sortBy: '',
    sortOrder: '',
  });
  const [pagination, setPagination] = useState({
    current: 1,
    pages: 1,
    total: 0,
  });
  const [loading, setLoading] = useState(true);
  const [statsLoading, setStatsLoading] = useState(true);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [error, setError] = useState('');

  // Fetch invoices
  const fetchInvoices = async () => {
    try {
      setLoading(true);
      setError('');
      const queryString = buildQueryString(filters);
      const response = await invoicesAPI.getAll(queryString);
      setInvoices(response.invoices);
      setPagination(response.pagination);
    } catch (err) {
      setError('Failed to fetch invoices');
      console.error('Error fetching invoices:', err);
    } finally {
      setLoading(false);
    }
  };

  // Fetch invoice statistics
  const fetchStats = async () => {
    try {
      setStatsLoading(true);
      const response = await invoicesAPI.getStats();
      setStats(response);
    } catch (err) {
      console.error('Error fetching invoice stats:', err);
    } finally {
      setStatsLoading(false);
    }
  };

  // Initial data fetch
  useEffect(() => {
    fetchInvoices();
    fetchStats();
  }, []);

  // Handle highlight parameter from URL
  useEffect(() => {
    if (highlightInvoiceId && invoices.length > 0) {
      const invoice = invoices.find(inv => inv._id === highlightInvoiceId);
      if (invoice) {
        setHighlightedInvoice(invoice);
        setShowDetailsModal(true);
        // Remove the highlight parameter from URL
        setSearchParams({});
      }
    }
  }, [highlightInvoiceId, invoices, setSearchParams]);

  // Fetch invoices when filters change
  useEffect(() => {
    fetchInvoices();
  }, [filters]);

  // Handle filter changes
  const handleFiltersChange = (newFilters: IInvoiceFilters) => {
    setFilters(newFilters);
  };

  // Reset filters
  const handleResetFilters = () => {
    setFilters({
      type: '',
      status: '',
      paymentStatus: '',
      paymentMethod: '',
      generatedFrom: '',
      autoGenerated: '',
      search: '',
      customerName: '',
      dateFrom: '',
      dateTo: '',
      dueDateFrom: '',
      dueDateTo: '',
      amountFrom: undefined,
      amountTo: undefined,
      createdBy: '',
      page: 1,
      limit: 10,
      sortBy: '',
      sortOrder: '',
    });
  };

  // Handle pagination
  const handlePageChange = (page: number) => {
    setFilters(prev => ({ ...prev, page }));
  };

  // Handle view invoice
  const handleViewInvoice = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setShowDetailsModal(true);
  };

  // Handle edit invoice
  const handleEditInvoice = (invoice: Invoice) => {
    // TODO: Implement edit functionality
    console.log('Edit invoice:', invoice);
  };

  // Handle delete invoice
  const handleDeleteInvoice = async (invoice: Invoice) => {
    if (!confirm(`Are you sure you want to delete invoice ${invoice.invoiceNumber}?`)) {
      return;
    }

    try {
      await invoicesAPI.delete(invoice._id);
      await fetchInvoices();
      await fetchStats();
    } catch (err) {
      console.error('Error deleting invoice:', err);
      alert('Failed to delete invoice');
    }
  };

  // Handle update payment
  const handleUpdatePayment = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setShowPaymentModal(true);
  };

  // Handle payment update submission
  const handlePaymentUpdate = async (invoiceId: string, paymentData: any) => {
    try {
      await invoicesAPI.updatePayment(invoiceId, paymentData);
      await fetchInvoices();
      await fetchStats();
      setShowPaymentModal(false);
      setSelectedInvoice(null);
    } catch (err) {
      throw new Error('Failed to update payment');
    }
  };

  // Handle modal close
  const handleCloseModals = () => {
    setShowDetailsModal(false);
    setShowPaymentModal(false);
    setSelectedInvoice(null);
    setHighlightedInvoice(null);
  };

  return (
    <Layout>
      <div className="p-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Invoices</h1>
            <p className="text-gray-600 mt-1">
              Manage your sales and purchase invoices
            </p>
          </div>
          <div className="flex space-x-3">
            <button
              onClick={() => fetchInvoices()}
              className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 transition-colors"
            >
              Refresh
            </button>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-md">
            <p className="text-red-600">{error}</p>
          </div>
        )}

        {/* Statistics */}
        <InvoiceStats stats={stats} loading={statsLoading} />

        {/* Filters */}
        <InvoiceFilters
          filters={filters}
          onFiltersChange={handleFiltersChange}
          onReset={handleResetFilters}
        />

        {/* Loading State */}
        {loading ? (
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
            <div className="animate-pulse space-y-4">
              {[...Array(5)].map((_, index) => (
                <div key={index} className="h-16 bg-gray-200 rounded"></div>
              ))}
            </div>
          </div>
        ) : (
          <>
            {/* Invoice Table */}
            <InvoiceTable
              invoices={invoices}
              highlightedInvoiceId={highlightInvoiceId ?? undefined}
              onViewInvoice={handleViewInvoice}
              onEditInvoice={handleEditInvoice}
              onDeleteInvoice={handleDeleteInvoice}
              onUpdatePayment={handleUpdatePayment}
            />

            {/* Pagination */}
            {pagination.pages > 1 && (
              <div className="flex items-center justify-between mt-6">
                <div className="text-sm text-gray-700">
                  Showing {((pagination.current - 1) * filters.limit!) + 1} to{' '}
                  {Math.min(pagination.current * filters.limit!, pagination.total)} of{' '}
                  {pagination.total} results
                </div>
                <div className="flex space-x-2">
                  <button
                    onClick={() => handlePageChange(pagination.current - 1)}
                    disabled={pagination.current === 1}
                    className="px-3 py-2 text-sm bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Previous
                  </button>
                  {[...Array(pagination.pages)].map((_, index) => {
                    const page = index + 1;
                    return (
                      <button
                        key={page}
                        onClick={() => handlePageChange(page)}
                        className={`px-3 py-2 text-sm rounded-md ${
                          page === pagination.current
                            ? 'bg-blue-600 text-white'
                            : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                        }`}
                      >
                        {page}
                      </button>
                    );
                  })}
                  <button
                    onClick={() => handlePageChange(pagination.current + 1)}
                    disabled={pagination.current === pagination.pages}
                    className="px-3 py-2 text-sm bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Next
                  </button>
                </div>
              </div>
            )}
          </>
        )}

        {/* Modals */}
        <InvoiceDetailsModal
          invoice={highlightedInvoice || selectedInvoice}
          isOpen={showDetailsModal}
          onClose={handleCloseModals}
          onEdit={handleEditInvoice}
          onUpdatePayment={handleUpdatePayment}
        />

        <PaymentUpdateModal
          invoice={selectedInvoice}
          isOpen={showPaymentModal}
          onClose={handleCloseModals}
          onUpdate={handlePaymentUpdate}
        />
      </div>
    </Layout>
  );
};

export default Invoices;