import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import Layout from '../layout/Layout';
import InvoiceStats from './Invoices/InvoiceStats';
import InvoiceFilters from './Invoices/InvoiceFilters';
import InvoiceTable from './Invoices/InvoiceTable';
import InvoiceDetailsModal from './Invoices/InvoiceDetailsModal';
import SendEmailModal from './Invoices/SendEmailModal';
import { Invoice, InvoiceStats as IInvoiceStats, InvoiceFilters as IInvoiceFilters, InvoiceResponse } from './Invoices/types';
import { buildQueryString } from './Invoices/utils';
import { invoicesAPI } from '../services/api';

const Invoices: React.FC = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const highlightInvoiceId = searchParams.get('highlight');
  
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [highlightedInvoice, setHighlightedInvoice] = useState<Invoice | null>(null);
  const [stats, setStats] = useState<IInvoiceStats>({
    totalInvoices: 0,
    totalAmount: 0,
    paidAmount: 0,
    pendingAmount: 0,
    salesInvoices: 0,
    purchaseInvoices: 0,
    paidInvoices: 0,
    unpaidInvoices: 0,
    partialInvoices: 0,
  });
  const [filters, setFilters] = useState<IInvoiceFilters>({
    type: '',
    status: '',
    paymentStatus: '',
    paymentMethod: '',
    generatedFrom: '',
    autoGenerated: '',
    search: '',
    customerName: '',
    dateFrom: '',
    dateTo: '',
    dueDateFrom: '',
    dueDateTo: '',
    amountFrom: undefined,
    amountTo: undefined,
    createdBy: '',
    page: 1,
    limit: 10,
    sortBy: 'createdAt',
    sortOrder: 'desc',
  });
  const [pagination, setPagination] = useState({
    current: 1,
    pages: 1,
    total: 0,
  });
  const [loading, setLoading] = useState(true);
  const [statsLoading, setStatsLoading] = useState(true);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailingInvoiceId, setEmailingInvoiceId] = useState<string | null>(null);
  const [error, setError] = useState('');

  // Fetch invoices
  const fetchInvoices = async () => {
    try {
      setLoading(true);
      setError('');
      const queryString = buildQueryString(filters);
      const response = await invoicesAPI.getAll(queryString);
      setInvoices(response.invoices);
      setPagination(response.pagination);
    } catch (err) {
      setError('Failed to fetch invoices');
      console.error('Error fetching invoices:', err);
    } finally {
      setLoading(false);
    }
  };

  // Fetch invoice statistics
  const fetchStats = async () => {
    try {
      setStatsLoading(true);
      const response = await invoicesAPI.getStats();
      setStats(response);
    } catch (err) {
      console.error('Error fetching invoice stats:', err);
    } finally {
      setStatsLoading(false);
    }
  };

  // Initial data fetch
  useEffect(() => {
    fetchInvoices();
    fetchStats();
  }, []);

  // Handle highlight parameter from URL
  useEffect(() => {
    const handleHighlight = async () => {
      if (highlightInvoiceId) {
        // First try to find the invoice in the current list
        let invoice = invoices.find(inv => inv._id === highlightInvoiceId);
        
        if (!invoice && invoices.length > 0) {
          // If not found in current list, try to fetch it directly
          try {
            invoice = await invoicesAPI.getById(highlightInvoiceId);
          } catch (error) {
            console.error('Error fetching highlighted invoice:', error);
            toast.error('Invoice not found');
            setSearchParams({});
            return;
          }
        }
        
        if (invoice) {
          setHighlightedInvoice(invoice);
          setShowDetailsModal(true);
          // Remove the highlight parameter from URL
          setSearchParams({});
        } else if (invoices.length === 0) {
          // If invoices haven't loaded yet, wait for them
          return;
        } else {
          // Invoice not found
          toast.error('Invoice not found');
          setSearchParams({});
        }
      }
    };

    handleHighlight();
  }, [highlightInvoiceId, invoices, setSearchParams]);

  // Fetch invoices when filters change
  useEffect(() => {
    fetchInvoices();
  }, [filters]);

  // Handle filter changes
  const handleFiltersChange = (newFilters: IInvoiceFilters) => {
    setFilters(newFilters);
  };

  // Reset filters
  const handleResetFilters = () => {
    setFilters({
      type: '',
      status: '',
      paymentStatus: '',
      paymentMethod: '',
      generatedFrom: '',
      autoGenerated: '',
      search: '',
      customerName: '',
      dateFrom: '',
      dateTo: '',
      dueDateFrom: '',
      dueDateTo: '',
      amountFrom: undefined,
      amountTo: undefined,
      createdBy: '',
      page: 1,
      limit: 10,
      sortBy: 'createdAt',
      sortOrder: 'desc',
    });
  };

  // Handle pagination
  const handlePageChange = (page: number) => {
    setFilters(prev => ({ ...prev, page }));
  };

  // Handle view invoice
  const handleViewInvoice = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setShowDetailsModal(true);
  };

  // Handle delete invoice
  const handleDeleteInvoice = async (invoice: Invoice) => {
    if (!confirm(`Are you sure you want to delete invoice ${invoice.invoiceNumber}?`)) {
      return;
    }

    try {
      await invoicesAPI.delete(invoice._id);
      await fetchInvoices();
      await fetchStats();
    } catch (err) {
      console.error('Error deleting invoice:', err);
      alert('Failed to delete invoice');
    }
  };

  const handleEmailInvoice = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setShowEmailModal(true);
  };

  const handleSendEmail = async (email: string) => {
    if (!selectedInvoice) return;

    try {
      setEmailingInvoiceId(selectedInvoice._id);
      await invoicesAPI.sendEmail(selectedInvoice._id, { email });
      toast.success(`Invoice sent to ${email}`);
    } catch (err: any) {
      const message = err?.message || 'Failed to send invoice email';
      toast.error(message);
      throw err;
    } finally {
      setEmailingInvoiceId(null);
    }
  };

  // Handle modal close
  const handleCloseModals = () => {
    setShowDetailsModal(false);
    setShowEmailModal(false);
    setSelectedInvoice(null);
    setHighlightedInvoice(null);
  };

  return (
    <Layout>
      <div className="p-3 sm:p-6">
        {/* Header */}
        <div className="flex flex-wrap items-center justify-between gap-3 mb-4 sm:mb-6">
          <div>
            <h1 className="text-xl sm:text-3xl font-bold text-gray-900">Invoices</h1>
            <p className="text-gray-600 mt-1 text-sm sm:text-base">Manage your sales and purchase invoices</p>
          </div>
          <div className="flex space-x-3">
            <button onClick={() => fetchInvoices()} className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 transition-colors text-sm">
              Refresh
            </button>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-md">
            <p className="text-red-600">{error}</p>
          </div>
        )}

        {/* Statistics */}
        <InvoiceStats stats={stats} loading={statsLoading} />

        {/* Filters */}
        <InvoiceFilters filters={filters} onFiltersChange={handleFiltersChange} onReset={handleResetFilters} />

        {/* Loading State */}
        {loading ? (
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
            <div className="animate-pulse space-y-4">
              {[...Array(5)].map((_, index) => (
                <div key={index} className="h-16 bg-gray-200 rounded"></div>
              ))}
            </div>
          </div>
        ) : (
          <>
            <InvoiceTable
              invoices={invoices}
              highlightedInvoiceId={highlightInvoiceId ?? undefined}
              onViewInvoice={handleViewInvoice}
              onDeleteInvoice={handleDeleteInvoice}
            />

            {/* Pagination */}
            {pagination.total > 0 && (
              <div className="flex flex-col sm:flex-row items-center justify-between gap-3 mt-4 p-4 border-t">
                <div className="flex flex-wrap items-center gap-3">
                  <div className="text-sm text-gray-700">
                    {((pagination.current - 1) * filters.limit!) + 1}–{Math.min(pagination.current * filters.limit!, pagination.total)} of {pagination.total}
                  </div>
                  <div className="flex items-center gap-2">
                    <label htmlFor="invoice-page-size" className="text-sm text-gray-600">Per page:</label>
                    <select
                      id="invoice-page-size"
                      value={filters.limit}
                      onChange={(e) => {
                        const newLimit = parseInt(e.target.value)
                        setFilters(prev => ({ ...prev, limit: newLimit, page: 1 }))
                        setPagination(prev => ({ ...prev, limit: newLimit, current: 1, pages: Math.ceil(prev.total / newLimit) }))
                      }}
                      className="px-2 py-1 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500"
                    >
                      <option value={10}>10</option>
                      <option value={25}>25</option>
                      <option value={50}>50</option>
                      <option value={100}>100</option>
                    </select>
                  </div>
                </div>
                {pagination.pages > 1 && (
                  <div className="flex items-center gap-2">
                    <button onClick={() => handlePageChange(pagination.current - 1)} disabled={pagination.current === 1} className="px-3 py-1.5 text-sm bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 disabled:opacity-50">Prev</button>
                    <span className="text-sm text-gray-600">{pagination.current} / {pagination.pages}</span>
                    <button onClick={() => handlePageChange(pagination.current + 1)} disabled={pagination.current === pagination.pages} className="px-3 py-1.5 text-sm bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 disabled:opacity-50">Next</button>
                  </div>
                )}
              </div>
            )}
          </>
        )}

        {/* Modals */}
        <InvoiceDetailsModal
          invoice={highlightedInvoice || selectedInvoice}
          isOpen={showDetailsModal}
          onClose={handleCloseModals}
          onEmailInvoice={handleEmailInvoice}
          emailSending={Boolean((highlightedInvoice || selectedInvoice)?._id && emailingInvoiceId === (highlightedInvoice || selectedInvoice)?._id)}
        />

        <SendEmailModal
          invoice={selectedInvoice}
          isOpen={showEmailModal}
          onClose={handleCloseModals}
          onSend={handleSendEmail}
          isSending={emailingInvoiceId === selectedInvoice?._id}
        />
      </div>
    </Layout>
  );
};

export default Invoices;