const mongoose = require("mongoose");

const invoiceSchema = new mongoose.Schema({
  invoiceNumber: {
    type: String,
    required: true,
    unique: true,
  },
  type: {
    type: String,
    enum: ["sale", "purchase"],
    required: true,
  },
  // Reference to original sale or purchase
  relatedId: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    refPath: 'relatedModel'
  },
  relatedModel: {
    type: String,
    required: true,
    enum: ['Sale', 'Purchase']
  },
  // Customer/Supplier information
  customerName: {
    type: String,
    required: true,
  },
  customerEmail: {
    type: String,
  },
  customerPhone: {
    type: String,
  },
  customerAddress: {
    street: String,
    city: String,
    state: String,
    zipCode: String,
    country: String,
  },
  // Company information
  companyInfo: {
    name: {
      type: String,
      default: "Your Company Name"
    },
    address: {
      street: String,
      city: String,
      state: String,
      zipCode: String,
      country: String,
    },
    phone: String,
    email: String,
    website: String,
    taxId: String,
  },
  items: [{
    inventoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Inventory",
    },
    name: {
      type: String,
      required: true,
    },
    description: String,
    quantity: {
      type: Number,
      required: true,
    },
    price: {
      type: Number,
      required: true,
    },
    total: {
      type: Number,
      required: true,
    },
  }],
  subtotal: {
    type: Number,
    required: true,
  },
  tax: {
    type: Number,
    default: 0,
  },
  discount: {
    type: Number,
    default: 0,
  },
  shipping: {
    type: Number,
    default: 0,
  },
  total: {
    type: Number,
    required: true,
  },
  dueDate: {
    type: Date,
    required: true,
  },
  issueDate: {
    type: Date,
    default: Date.now,
  },
  status: {
    type: String,
    enum: ["draft", "sent", "paid", "partial", "overdue", "cancelled"],
    default: "draft",
  },
  paymentStatus: {
    type: String,
    enum: ["unpaid", "partial", "paid"],
    default: "unpaid",
  },
  paidAmount: {
    type: Number,
    default: 0,
  },
  paymentMethod: {
    type: String,
    enum: ["cash", "card", "bank_transfer", "credit", "other"],
  },
  paymentTerms: {
    type: String,
    default: "Net 30",
  },
  notes: {
    type: String,
  },
  // Auto-generation tracking
  autoGenerated: {
    type: Boolean,
    default: false,
  },
  generatedFrom: {
    type: String,
    enum: ["sale", "purchase", "manual"],
    default: "manual",
  },
  // User tracking
  createdBy: {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    name: String,
    role: String,
  },
}, {
  timestamps: true,
});

// Generate invoice number automatically
invoiceSchema.pre('save', async function(next) {
  if (this.isNew && !this.invoiceNumber) {
    try {
      const prefix = this.type === 'sale' ? 'INV' : 'PINV';
      const count = await this.constructor.countDocuments({ type: this.type });
      this.invoiceNumber = `${prefix}-${String(count + 1).padStart(6, '0')}`;
    } catch (error) {
      console.error('Error generating invoice number:', error);
      // Fallback to timestamp-based number if count fails
      const prefix = this.type === 'sale' ? 'INV' : 'PINV';
      const timestamp = Date.now().toString().slice(-6);
      this.invoiceNumber = `${prefix}-${timestamp}`;
    }
  }
  next();
});

module.exports = mongoose.model("Invoice", invoiceSchema);

