import React, { useState } from 'react';
import { SearchIcon, FilterIcon, XIcon, ArrowUpIcon, ArrowDownIcon } from 'lucide-react';
import { InvoiceFilters as IInvoiceFilters } from './types';

interface InvoiceFiltersProps {
  filters: IInvoiceFilters;
  onFiltersChange: (filters: IInvoiceFilters) => void;
  onReset: () => void;
}

const InvoiceFilters: React.FC<InvoiceFiltersProps> = ({
  filters,
  onFiltersChange,
  onReset,
}) => {
  const [showAdvanced, setShowAdvanced] = useState(false);

  const handleFilterChange = (key: keyof IInvoiceFilters, value: string | number) => {
    onFiltersChange({
      ...filters,
      [key]: value,
      page: 1, // Reset to first page when filters change
    });
  };

  const formatDateForInput = (dateString?: string) => {
    if (!dateString) return '';
    return new Date(dateString).toISOString().split('T')[0];
  };

  const toggleSortDirection = () => {
    const newDirection = filters.sortOrder === 'asc' ? 'desc' : 'asc';
    onFiltersChange({
      ...filters,
      sortOrder: newDirection,
      page: 1,
    });
  };

  const hasActiveFilters =
    filters.type !== '' ||
    filters.status !== '' ||
    filters.paymentStatus !== '' ||
    filters.paymentMethod !== '' ||
    filters.generatedFrom !== '' ||
    filters.autoGenerated !== '' ||
    filters.customerName !== '' ||
    filters.dateFrom !== '' ||
    filters.dateTo !== '' ||
    filters.dueDateFrom !== '' ||
    filters.dueDateTo !== '' ||
    (filters.amountFrom !== undefined && filters.amountFrom > 0) ||
    (filters.amountTo !== undefined && filters.amountTo > 0) ||
    filters.createdBy !== '';

  return (
    <div className="bg-white p-5 rounded-lg shadow-sm border border-gray-200 mb-6">
      {/* Main Filter Row */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        {/* Search Bar */}
        <div className="relative flex-1">
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <SearchIcon size={18} className="text-gray-400" />
          </div>
          <input
            type="text"
            placeholder="Search by invoice number, customer..."
            value={filters.search || ''}
            onChange={(e) => handleFilterChange('search', e.target.value)}
            className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg w-full focus:outline-none focus:ring-2 focus:ring-teal-500"
          />
        </div>

        {/* Type Filter */}
        <select
          value={filters.type || ''}
          onChange={(e) => handleFilterChange('type', e.target.value)}
          className="border border-gray-300 rounded-lg py-2 px-4 bg-white focus:outline-none focus:ring-2 focus:ring-teal-500"
        >
          <option value="">All Types</option>
          <option value="sale">Sales Invoice</option>
          <option value="purchase">Purchase Invoice</option>
        </select>

        {/* Status Filter */}
        <select
          value={filters.status || ''}
          onChange={(e) => handleFilterChange('status', e.target.value)}
          className="border border-gray-300 rounded-lg py-2 px-4 bg-white focus:outline-none focus:ring-2 focus:ring-teal-500"
        >
          <option value="">All Status</option>
          <option value="draft">Draft</option>
          <option value="sent">Sent</option>
          <option value="paid">Paid</option>
          <option value="partial">Partially Paid</option>
          <option value="overdue">Overdue</option>
          <option value="cancelled">Cancelled</option>
        </select>

        {/* Payment Status Filter */}
        <select
          value={filters.paymentStatus || ''}
          onChange={(e) => handleFilterChange('paymentStatus', e.target.value)}
          className="border border-gray-300 rounded-lg py-2 px-4 bg-white focus:outline-none focus:ring-2 focus:ring-teal-500"
        >
          <option value="">All Payment Status</option>
          <option value="unpaid">Unpaid</option>
          <option value="partial">Partially Paid</option>
          <option value="paid">Paid</option>
        </select>

        {/* Sort Controls */}
        <div className="flex items-center gap-2">
          <select
            value={filters.sortBy || 'createdAt'}
            onChange={(e) => handleFilterChange('sortBy', e.target.value)}
            className="border border-gray-300 rounded-lg py-2 px-3 bg-white focus:outline-none focus:ring-2 focus:ring-teal-500 text-sm"
          >
            <option value="createdAt">Sort by Date</option>
            <option value="dueDate">Sort by Due Date</option>
            <option value="total">Sort by Amount</option>
            <option value="invoiceNumber">Sort by Invoice #</option>
            <option value="customerName">Sort by Customer</option>
          </select>
          <button
            onClick={toggleSortDirection}
            className={`border border-gray-300 rounded-lg p-2 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-teal-500 ${
              filters.sortOrder === 'desc' ? 'bg-teal-50 border-teal-300' : 'bg-white'
            }`}
            title={filters.sortOrder === 'desc' ? 'Newest first (click for oldest first)' : 'Oldest first (click for newest first)'}
          >
            {filters.sortOrder === 'desc' ? (
              <ArrowDownIcon size={18} className="text-teal-600" />
            ) : (
              <ArrowUpIcon size={18} className="text-gray-600" />
            )}
          </button>
        </div>

        {/* Filters Button */}
        <button
          onClick={() => setShowAdvanced(!showAdvanced)}
          className={`border border-gray-300 text-gray-700 py-2 px-4 rounded-lg flex items-center hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-teal-500 ${
            hasActiveFilters ? 'bg-teal-50 border-teal-300' : 'bg-white'
          }`}
        >
          <FilterIcon size={18} className="mr-2" />
          <span>Filters</span>
          {hasActiveFilters && (
            <span className="ml-2 bg-teal-500 text-white rounded-full w-5 h-5 flex items-center justify-center text-xs">
              !
            </span>
          )}
        </button>

        {/* Clear Filters Button */}
        {hasActiveFilters && (
          <button
            onClick={onReset}
            className="text-gray-600 hover:text-red-600 py-2 px-3 flex items-center focus:outline-none"
            title="Clear all filters"
          >
            <XIcon size={18} />
          </button>
        )}
      </div>

      {/* Advanced Filters */}
      {showAdvanced && (
        <div className="mt-4 p-5 border border-gray-200 rounded-lg bg-gray-50 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-700 mb-4">Advanced Filters</h3>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {/* Payment Method Filter */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Payment Method</label>
              <select
                value={filters.paymentMethod || ''}
                onChange={(e) => handleFilterChange('paymentMethod', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              >
                <option value="">All Methods</option>
                <option value="cash">Cash</option>
                <option value="card">Card</option>
                <option value="bank_transfer">Bank Transfer</option>
                <option value="credit">Credit</option>
                <option value="other">Other</option>
              </select>
            </div>

            {/* Generated From Filter */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Generated From</label>
              <select
                value={filters.generatedFrom || ''}
                onChange={(e) => handleFilterChange('generatedFrom', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              >
                <option value="">All Sources</option>
                <option value="sale">From Sale</option>
                <option value="purchase">From Purchase</option>
                <option value="manual">Manual Entry</option>
              </select>
            </div>

            {/* Auto Generated Filter */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Auto Generated</label>
              <select
                value={filters.autoGenerated || ''}
                onChange={(e) => handleFilterChange('autoGenerated', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              >
                <option value="">All</option>
                <option value="true">Auto Generated</option>
                <option value="false">Manual</option>
              </select>
            </div>

            {/* Customer Name Filter */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Customer Name</label>
              <input
                type="text"
                placeholder="Customer name..."
                value={filters.customerName || ''}
                onChange={(e) => handleFilterChange('customerName', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              />
            </div>

            {/* Created By Filter */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Created By</label>
              <input
                type="text"
                placeholder="Creator name..."
                value={filters.createdBy || ''}
                onChange={(e) => handleFilterChange('createdBy', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              />
            </div>

            {/* Date From */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Issue Date From</label>
              <input
                type="date"
                value={formatDateForInput(filters.dateFrom)}
                onChange={(e) => handleFilterChange('dateFrom', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              />
            </div>

            {/* Date To */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Issue Date To</label>
              <input
                type="date"
                value={formatDateForInput(filters.dateTo)}
                onChange={(e) => handleFilterChange('dateTo', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              />
            </div>

            {/* Due Date From */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Due Date From</label>
              <input
                type="date"
                value={formatDateForInput(filters.dueDateFrom)}
                onChange={(e) => handleFilterChange('dueDateFrom', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              />
            </div>

            {/* Due Date To */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Due Date To</label>
              <input
                type="date"
                value={formatDateForInput(filters.dueDateTo)}
                onChange={(e) => handleFilterChange('dueDateTo', e.target.value)}
                className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white"
              />
            </div>

            {/* Amount Range */}
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-600 block">Amount (Rs)</label>
              <div className="flex gap-2 items-center">
                <input
                  type="number"
                  placeholder="Min"
                  min="0"
                  step="0.01"
                  value={filters.amountFrom || ''}
                  onChange={(e) => handleFilterChange('amountFrom', parseFloat(e.target.value) || 0)}
                  className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                />
                <span className="text-gray-400">-</span>
                <input
                  type="number"
                  placeholder="Max"
                  min="0"
                  step="0.01"
                  value={filters.amountTo || ''}
                  onChange={(e) => handleFilterChange('amountTo', parseFloat(e.target.value) || 0)}
                  className="border border-gray-300 rounded-lg py-2 px-3 w-full text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default InvoiceFilters;