import React from 'react';
import { Invoice } from './types';
import {
  formatCurrency,
  formatDate,
  getStatusColor,
  getPaymentStatusColor,
  getTypeColor,
  getInvoiceTypeLabel,
  getStatusLabel,
  getPaymentStatusLabel,
  isOverdue,
  calculateRemainingAmount,
} from './utils';

interface InvoiceTableProps {
  invoices: Invoice[];
  highlightedInvoiceId?: string;
  onViewInvoice: (invoice: Invoice) => void;
  onDeleteInvoice: (invoice: Invoice) => void;
  onUpdatePayment: (invoice: Invoice) => void;
}

const InvoiceTable: React.FC<InvoiceTableProps> = ({
  invoices,
  highlightedInvoiceId,
  onViewInvoice,
  onDeleteInvoice,
  onUpdatePayment,
}) => {
  if (invoices.length === 0) {
    return (
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8 text-center">
        <div className="text-gray-500">
          <svg
            className="mx-auto h-12 w-12 text-gray-400 mb-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
            />
          </svg>
          <h3 className="text-lg font-medium text-gray-900 mb-2">No invoices found</h3>
          <p className="text-gray-500">
            No invoices match your current filters. Try adjusting your search criteria.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Invoice
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Customer/Supplier
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Type
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Amount
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Status
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Payment
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Due Date
              </th>
              <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {invoices.map((invoice) => {
              const isHighlighted = highlightedInvoiceId === invoice._id;
              return (
                <tr
                  key={invoice._id}
                  className={`hover:bg-gray-50 ${
                    isOverdue(invoice) ? 'bg-red-50' : ''
                  } ${
                    isHighlighted ? 'bg-blue-50 border-l-4 border-blue-500' : ''
                  }`}
                >
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div>
                      <div className={`text-sm font-medium ${isHighlighted ? 'text-blue-900' : 'text-gray-900'}`}>
                        {invoice.invoiceNumber}
                        {isHighlighted && (
                          <span className="ml-2 inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">
                            Highlighted
                          </span>
                        )}
                      </div>
                      <div className="text-sm text-gray-500">
                        {formatDate(invoice.issueDate)}
                      </div>
                      {invoice.autoGenerated && (
                        <div className="text-xs text-blue-600">Auto-generated</div>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-gray-900">
                      {invoice.customerName}
                    </div>
                    {invoice.customerEmail && (
                      <div className="text-sm text-gray-500">
                        {invoice.customerEmail}
                      </div>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span
                      className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getTypeColor(
                        invoice.type
                      )}`}
                    >
                      {getInvoiceTypeLabel(invoice.type)}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-gray-900">
                      {formatCurrency(invoice.total)}
                    </div>
                    {invoice.paidAmount > 0 && (
                      <div className="text-sm text-gray-500">
                        Paid: {formatCurrency(invoice.paidAmount)}
                      </div>
                    )}
                    {calculateRemainingAmount(invoice) > 0 && (
                      <div className="text-sm text-red-600">
                        Due: {formatCurrency(calculateRemainingAmount(invoice))}
                      </div>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span
                      className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getStatusColor(
                        invoice.status
                      )}`}
                    >
                      {getStatusLabel(invoice.status)}
                    </span>
                    {isOverdue(invoice) && (
                      <div className="text-xs text-red-600 mt-1">Overdue</div>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span
                      className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getPaymentStatusColor(
                        invoice.paymentStatus
                      )}`}
                    >
                      {getPaymentStatusLabel(invoice.paymentStatus)}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {formatDate(invoice.dueDate)}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <div className="flex justify-end space-x-2">
                      <button
                        onClick={() => onViewInvoice(invoice)}
                        className="text-blue-600 hover:text-blue-900 text-sm"
                        title="View Invoice"
                      >
                        View
                      </button>
                      {invoice.paymentStatus !== 'paid' && (
                        <button
                          onClick={() => onUpdatePayment(invoice)}
                          className="text-green-600 hover:text-green-900 text-sm"
                          title="Update Payment"
                        >
                          Payment
                        </button>
                      )}
                      <button
                        onClick={() => onDeleteInvoice(invoice)}
                        className="text-red-600 hover:text-red-900 text-sm"
                        title="Delete Invoice"
                      >
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default InvoiceTable;