export interface InvoiceItem {
  _id?: string;
  inventoryId?: string;
  name: string;
  description?: string;
  quantity: number;
  price: number;
  total: number;
}

export interface CustomerAddress {
  street?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
}

export interface CompanyInfo {
  name: string;
  address?: CustomerAddress;
  phone?: string;
  email?: string;
  website?: string;
  taxId?: string;
}

export interface CreatedBy {
  userId?: string;
  name: string;
  role: string;
}

export interface Invoice {
  _id: string;
  invoiceNumber: string;
  type: 'sale' | 'purchase';
  relatedId: string;
  relatedModel: 'Sale' | 'Purchase';
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  customerAddress?: CustomerAddress;
  companyInfo?: CompanyInfo;
  items: InvoiceItem[];
  subtotal: number;
  tax: number;
  discount: number;
  shipping?: number;
  total: number;
  dueDate: string;
  issueDate: string;
  status: 'draft' | 'sent' | 'paid' | 'partial' | 'overdue' | 'cancelled';
  paymentStatus: 'unpaid' | 'partial' | 'paid';
  paidAmount: number;
  paymentMethod?: 'cash' | 'card' | 'bank_transfer' | 'credit' | 'other';
  paymentTerms: string;
  notes?: string;
  autoGenerated: boolean;
  generatedFrom: 'sale' | 'purchase' | 'manual';
  createdBy?: CreatedBy;
  createdAt: string;
  updatedAt: string;
}

export interface InvoiceStats {
  totalInvoices: number;
  totalAmount: number;
  paidAmount: number;
  pendingAmount: number;
  salesInvoices: number;
  purchaseInvoices: number;
  paidInvoices: number;
  unpaidInvoices: number;
  partialInvoices: number;
}

export interface InvoiceFilters {
  type?: 'sale' | 'purchase' | '';
  status?: 'draft' | 'sent' | 'paid' | 'partial' | 'overdue' | 'cancelled' | '';
  paymentStatus?: 'unpaid' | 'partial' | 'paid' | '';
  paymentMethod?: 'cash' | 'card' | 'bank_transfer' | 'credit' | 'other' | '';
  generatedFrom?: 'sale' | 'purchase' | 'manual' | '';
  autoGenerated?: 'true' | 'false' | '';
  search?: string;
  customerName?: string;
  dateFrom?: string;
  dateTo?: string;
  dueDateFrom?: string;
  dueDateTo?: string;
  amountFrom?: number;
  amountTo?: number;
  createdBy?: string;
  page?: number;
  limit?: number;
  sortBy?: 'createdAt' | 'dueDate' | 'total' | 'invoiceNumber' | '';
  sortOrder?: 'asc' | 'desc' | '';
}

export interface PaginationInfo {
  current: number;
  pages: number;
  total: number;
}

export interface InvoiceResponse {
  invoices: Invoice[];
  pagination: PaginationInfo;
}